In [1]:
#import os
#os.chdir('C:\MM\Tools\PyTorch\PyTorch Fundamentals\Local_CONDA_Env\Last-Layer Fairness Fine-tuning is Simple and Effective for Neural Networks/UTKFace')

In [1]:
pwd



'/gpfs/space/home/sulaiman/MM/UTKFace'

In [2]:
ls

240_train_age_gender_detection_240_train_age_v3_batch_1024.ipynb
240_train_age_gender_detection_240_train_age_v3_batch_128_08_27_2023.ipynb
Destination_FolderName/
models.py
__pycache__/
UTKFace/
UTKFace.tar.gz


In [3]:

# importing the "tarfile" module
#import tarfile
  
# open file
#file = tarfile.open('UTKFace.tar.gz')
  
# extracting file
#file.extractall('./Destination_FolderName')
  
#file.close()

In [4]:
import os

folder_path = "Destination_FolderName/UTKFace"  # Replace with the actual folder path

image_extensions = [".jpg", ".jpeg", ".png", ".gif", ".bmp"]  # Add more if needed

image_count = 0

for filename in os.listdir(folder_path):
    if any(filename.lower().endswith(ext) for ext in image_extensions):
        image_count += 1

print(f"Number of images in the folder: {image_count}")


Number of images in the folder: 23708


In [1]:
# https://youtu.be/rdjWDAYt98s
"""
Train deep learning models to predict age and gender.

Datase from here: https://susanqq.github.io/UTKFace/
"""

import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import cv2
#from keras.models import Sequential,load_model,Model
#from keras.layers import Conv2D,MaxPool2D,Dense,Dropout,BatchNormalization,Flatten,Input
from sklearn.model_selection import train_test_split

import torch


In [6]:
path = "Destination_FolderName/UTKFace"
images_data = []
age = []
gender = []
age_gender = []
i = 0

for img in os.listdir(path):
  ages = img.split("_")[0]
  #print(np.array(ages))
  #print(type(np.array(ages)))
  if int(ages) > 35 :
    ages = 0
  else:
    ages = 1
  genders = img.split("_")[1]
  img = cv2.imread(str(path)+"/"+str(img))
  img = cv2.cvtColor(img,cv2.COLOR_BGR2RGB)
  img = np.array(img)
  tensor = torch.tensor(img)
  transposed_image = tensor.permute(2, 0, 1)
  images_data.append(transposed_image)
  age.append(np.array(ages))
  gender.append(np.array(genders))
  age_gender.append(torch.tensor([np.array(ages,np.uint64).tolist(), np.array(genders[0],np.uint64).tolist()]))
  #i = i +1
  #if i == 100:
   # break
  
#age = np.array(age,dtype=np.int64)
#images = np.array(images)   #Forgot to scale image for my training. Please divide by 255 to scale. 
#gender = np.array(gender,np.uint64)

#x_train_age, x_test_age, y_train_age, y_test_age = train_test_split(images, age, random_state=42)

#x_train_gender, x_test_gender, y_train_gender, y_test_gender = train_test_split(images, gender, random_state=42)

In [7]:
images_data[0]

tensor([[[ 80,  79,  78,  ..., 174, 174, 174],
         [ 80,  80,  79,  ..., 174, 174, 174],
         [ 80,  80,  79,  ..., 174, 174, 174],
         ...,
         [111, 109, 108,  ...,  73,  73,  73],
         [111, 109, 107,  ...,  67,  67,  67],
         [112, 109, 107,  ...,  63,  63,  64]],

        [[ 59,  58,  57,  ..., 174, 174, 174],
         [ 59,  59,  58,  ..., 174, 174, 174],
         [ 60,  60,  59,  ..., 174, 174, 174],
         ...,
         [ 82,  80,  77,  ...,  61,  61,  61],
         [ 82,  80,  76,  ...,  55,  55,  55],
         [ 83,  80,  76,  ...,  51,  51,  52]],

        [[ 54,  53,  52,  ..., 176, 176, 176],
         [ 54,  54,  53,  ..., 176, 176, 176],
         [ 53,  53,  52,  ..., 176, 176, 176],
         ...,
         [ 64,  62,  59,  ...,  61,  61,  61],
         [ 64,  62,  58,  ...,  55,  55,  55],
         [ 65,  62,  58,  ...,  51,  51,  52]]], dtype=torch.uint8)

# Split the data

In [6]:
print('(1: Young (age ≤ 35)):', int(age_gender[0][0]))

print('(0: Old (age > 35)):', int(age_gender[0][0]))

(1: Young (age ≤ 35)): 0
(0: Old (age > 35)): 0


In [75]:
print('(0: Male):', int(age_gender[0][1]))

print('(1: Female):', int(age_gender[0][1]))

(0: Male): 0
(1: Female): 0


In [76]:
print(len(images_data))

print(len(age_gender))

23708
23708


In [81]:
for k in range(len(images_data)):
    if int(age_gender[k][0]) == 1:
        print('(1: Young (age ≤ 35)):')
    elif int(age_gender[k][0]) == 0:
        print('(0: Old (age > 35)):')
    elif int(age_gender[k][1]) == 0:
        print('(0: Male):')
    elif int(age_gender[k][1]) == 1:
        print('(1: Female):')
        
    print(k)
    print(age_gender[k])
   
    break


(0: Old (age > 35)):
0
tensor([0, 0])


In [84]:
for k in range(len(images_data)):
    if int(age_gender[k][0]) == 1:
        print('(1: Young (age ≤ 35)):')
        if int(age_gender[k][1]) == 0:
            print('(0: Male):')
        elif int(age_gender[k][1]) == 1:
            print('(1: Female):')
    elif int(age_gender[k][0]) == 0:
        print('(0: Old (age > 35)):')
        if int(age_gender[k][1]) == 0:
            print('(0: Male):')
        elif int(age_gender[k][1]) == 1:
            print('(1: Female):')
        
    #print(k)
    print(age_gender[k])
   
    break


(0: Old (age > 35)):
(0: Male):
tensor([0, 0])


In [101]:
images_data_train = []
images_data_val = []
images_data_test = []

age_gender_train = []
age_gender_val = []
age_gender_test = []

In [102]:
for k in range(len(images_data)):
    if int(age_gender[k][0]) == 1:
        #print('(1: Young (age ≤ 35)):')
        if int(age_gender[k][1]) == 0:
            #print('(0: Male):')
            # 4,133/1,378/1,378
            if len(images_data_train) < 4133:
                images_data_train.append(images_data[k])
                age_gender_train.append(age_gender[k])
            elif len(images_data_val) < 1378:
                images_data_val.append(images_data[k])
                age_gender_val.append(age_gender[k])
            elif len(images_data_test) < 1378:
                images_data_test.append(images_data[k])
                age_gender_test.append(age_gender[k])
        elif int(age_gender[k][1]) == 1:
            #print('(1: Female):')
            # 4,931/1,643/1,644
            if len(images_data_train) < 4931:
                images_data_train.append(images_data[k])
                age_gender_train.append(age_gender[k])
            elif len(images_data_val) < 1643:
                images_data_val.append(images_data[k])
                age_gender_val.append(age_gender[k])
            elif len(images_data_test) < 1644:
                images_data_test.append(images_data[k])
                age_gender_test.append(age_gender[k])
    elif int(age_gender[k][0]) == 0:
        #print('(0: Old (age > 35)):')
        if int(age_gender[k][1]) == 0:
            #print('(0: Male):')
            #3,301/1,101/1,100
            if len(images_data_train) < 3301:
                images_data_train.append(images_data[k])
                age_gender_train.append(age_gender[k])
            elif len(images_data_val) < 1101:
                images_data_val.append(images_data[k])
                age_gender_val.append(age_gender[k])
            elif len(images_data_test) < 1100:
                images_data_test.append(images_data[k])
                age_gender_test.append(age_gender[k])
        elif int(age_gender[k][1]) == 1:
            #print('(1: Female):')
            #1,858/619/619
            if len(images_data_train) < 1858:
                images_data_train.append(images_data[k])
                age_gender_train.append(age_gender[k])
            elif len(images_data_val) < 619:
                images_data_val.append(images_data[k])
                age_gender_val.append(age_gender[k])
            elif len(images_data_test) < 619:
                images_data_test.append(images_data[k])
                age_gender_test.append(age_gender[k])
        
    #print(k)
    #print(age_gender[k])
   
    #break


In [105]:
print(len(images_data_train))
print(len(age_gender_train))

print('-------------------------')
print(len(images_data_val))
print(len(age_gender_val))
print('-------------------------')


print(len(images_data_test))
print(len(age_gender_test))
print('-------------------------')




4931
4931
-------------------------
1643
1643
-------------------------
1644
1644
-------------------------


In [8]:
images_data_train_Young_Male = []  # 4,133/1,378/1,378
age_gender_train_Young_Male = []  

images_data_train_Young_Female = [] # 4,931/1,643/1,644
age_gender_train_Young_Female = []

images_data_train_Old_Male = []  # 3,301/1,101/1,100
age_gender_train_Old_Male = []

images_data_train_Old_Female = []   # 1,858/619/619
age_gender_train_Old_Female = []

#####################################

images_data_val_Young_Male = []
age_gender_val_Young_Male = []

images_data_val_Young_Female = []
age_gender_val_Young_Female = []

images_data_val_Old_Male = []
age_gender_val_Old_Male = []

images_data_val_Old_Female = []
age_gender_val_Old_Female = []

#####################################

images_data_test_Young_Male = []
age_gender_test_Young_Male = []

images_data_test_Young_Female = []
age_gender_test_Young_Female = []

images_data_test_Old_Male = []
age_gender_test_Old_Male = []

images_data_test_Old_Female = []
age_gender_test_Old_Female = []

#####################################




In [9]:
for k in range(len(images_data)):
    if int(age_gender[k][0]) == 1:
        #print('(1: Young (age ≤ 35)):')
        if int(age_gender[k][1]) == 0:
            #print('(0: Male):')
            # 4,133/1,378/1,378
            if len(images_data_train_Young_Male) < 4133:
                images_data_train_Young_Male.append(images_data[k])
                age_gender_train_Young_Male.append(age_gender[k])
            elif len(images_data_val_Young_Male) < 1378:
                images_data_val_Young_Male.append(images_data[k])
                age_gender_val_Young_Male.append(age_gender[k])
            elif len(images_data_test_Young_Male) < 1378:
                images_data_test_Young_Male.append(images_data[k])
                age_gender_test_Young_Male.append(age_gender[k])
        elif int(age_gender[k][1]) == 1:
            #print('(1: Female):')
            # 4,931/1,643/1,644
            if len(images_data_train_Young_Female) < 4931:
                images_data_train_Young_Female.append(images_data[k])
                age_gender_train_Young_Female.append(age_gender[k])
            elif len(images_data_val_Young_Female) < 1643:
                images_data_val_Young_Female.append(images_data[k])
                age_gender_val_Young_Female.append(age_gender[k])
            elif len(images_data_test_Young_Female) < 1644:
                images_data_test_Young_Female.append(images_data[k])
                age_gender_test_Young_Female.append(age_gender[k])
    elif int(age_gender[k][0]) == 0:
        #print('(0: Old (age > 35)):')
        if int(age_gender[k][1]) == 0:
            #print('(0: Male):')
            #3,301/1,101/1,100
            if len(images_data_train_Old_Male) < 3301:
                images_data_train_Old_Male.append(images_data[k])
                age_gender_train_Old_Male.append(age_gender[k])
            elif len(images_data_val_Old_Male) < 1101:
                images_data_val_Old_Male.append(images_data[k])
                age_gender_val_Old_Male.append(age_gender[k])
            elif len(images_data_test_Old_Male) < 1100:
                images_data_test_Old_Male.append(images_data[k])
                age_gender_test_Old_Male.append(age_gender[k])
        elif int(age_gender[k][1]) == 1:
            #print('(1: Female):')
            #1,858/619/619
            if len(images_data_train_Old_Female) < 1858:
                images_data_train_Old_Female.append(images_data[k])
                age_gender_train_Old_Female.append(age_gender[k])
            elif len(images_data_val_Old_Female) < 619:
                images_data_val_Old_Female.append(images_data[k])
                age_gender_val_Old_Female.append(age_gender[k])
            elif len(images_data_test_Old_Female) < 619:
                images_data_test_Old_Female.append(images_data[k])
                age_gender_test_Old_Female.append(age_gender[k])
        
    #print(k)
    #print(age_gender[k])
   
    #break


In [10]:
print('images_data_train_Young_Male:', len(images_data_train_Young_Male))  # 4,133/1,378/1,378
print(len(age_gender_train_Young_Male))  



print('images_data_train_Young_Female:', len(images_data_train_Young_Female)) # 4,931/1,643/1,644
print(len(age_gender_train_Young_Female))



print('images_data_train_Old_Male:', len(images_data_train_Old_Male))  # 3,301/1,101/1,100
print(len(age_gender_train_Old_Male))




print('images_data_train_Old_Female:', len(images_data_train_Old_Female))   # 1,858/619/619
print(len(age_gender_train_Old_Female))
print('---------------    Val   ---------------------------')
#####################################




print(len(images_data_val_Young_Male))
print(len(age_gender_val_Young_Male))


print(len(images_data_val_Young_Female))
print(len(age_gender_val_Young_Female))


print(len(images_data_val_Old_Male))
print(len(age_gender_val_Old_Male))


print(len(images_data_val_Old_Female))
print(len(age_gender_val_Old_Female))
print('-----------------  Test -------------------------')




#####################################
print('------------------------------------------')
print(len(images_data_test_Young_Male))
print(len(age_gender_test_Young_Male))

print(len(images_data_test_Young_Female))
print(len(age_gender_test_Young_Female))

print(len(images_data_test_Old_Male))
print(len(age_gender_test_Old_Male))

print(len(images_data_test_Old_Female))
print(len(age_gender_test_Old_Female))
print('------------------------------------------')
#####################################




images_data_train_Young_Male: 4133
4133
images_data_train_Young_Female: 4931
4931
images_data_train_Old_Male: 3301
3301
images_data_train_Old_Female: 1858
1858
---------------    Val   ---------------------------
1378
1378
1643
1643
1101
1101
619
619
-----------------  Test -------------------------
------------------------------------------
1378
1378
1644
1644
1100
1100
619
619
------------------------------------------


In [11]:
all_images_data_train = images_data_train_Young_Male + images_data_train_Young_Female + images_data_train_Old_Male + images_data_train_Old_Female
all_images_data_val =  images_data_val_Young_Male + images_data_val_Young_Female + images_data_val_Old_Male + images_data_val_Old_Female
all_images_data_test = images_data_test_Young_Male + images_data_test_Young_Female + images_data_test_Old_Male + images_data_test_Old_Female

all_age_gender_train = age_gender_train_Young_Male + age_gender_train_Young_Female + age_gender_train_Old_Male + age_gender_train_Old_Female
all_age_gender_val =  age_gender_val_Young_Male + age_gender_val_Young_Female + age_gender_val_Old_Male + age_gender_val_Old_Female
all_age_gender_test = age_gender_test_Young_Male + age_gender_test_Young_Female + age_gender_test_Old_Male + age_gender_test_Old_Female


In [12]:
print(len(all_images_data_train))
print(len(all_images_data_val))
print(len(all_images_data_test))

14223
4741
4741


In [13]:
all_images_data_train[0].shape

torch.Size([3, 200, 200])

In [14]:
print(len(all_age_gender_train))
print(len(all_age_gender_val))
print(len(all_age_gender_test))


14223
4741
4741


In [49]:
print(type(all_images_data_train))
print(type(all_images_data_train))

<class 'list'>
<class 'list'>


In [60]:
all_age_gender_test

[tensor([1, 0]),
 tensor([1, 0]),
 tensor([1, 0]),
 tensor([1, 0]),
 tensor([1, 0]),
 tensor([1, 0]),
 tensor([1, 0]),
 tensor([1, 0]),
 tensor([1, 0]),
 tensor([1, 0]),
 tensor([1, 0]),
 tensor([1, 0]),
 tensor([1, 0]),
 tensor([1, 0]),
 tensor([1, 0]),
 tensor([1, 0]),
 tensor([1, 0]),
 tensor([1, 0]),
 tensor([1, 0]),
 tensor([1, 0]),
 tensor([1, 0]),
 tensor([1, 0]),
 tensor([1, 0]),
 tensor([1, 0]),
 tensor([1, 0]),
 tensor([1, 0]),
 tensor([1, 0]),
 tensor([1, 0]),
 tensor([1, 0]),
 tensor([1, 0]),
 tensor([1, 0]),
 tensor([1, 0]),
 tensor([1, 0]),
 tensor([1, 0]),
 tensor([1, 0]),
 tensor([1, 0]),
 tensor([1, 0]),
 tensor([1, 0]),
 tensor([1, 0]),
 tensor([1, 0]),
 tensor([1, 0]),
 tensor([1, 0]),
 tensor([1, 0]),
 tensor([1, 0]),
 tensor([1, 0]),
 tensor([1, 0]),
 tensor([1, 0]),
 tensor([1, 0]),
 tensor([1, 0]),
 tensor([1, 0]),
 tensor([1, 0]),
 tensor([1, 0]),
 tensor([1, 0]),
 tensor([1, 0]),
 tensor([1, 0]),
 tensor([1, 0]),
 tensor([1, 0]),
 tensor([1, 0]),
 tensor([1, 0]

In [53]:
type(all_age_gender_test)

list

In [50]:
torch.save(all_age_gender_test, 'all_age_gender_test_tensor.pt')

In [51]:
pwd

'/gpfs/space/home/sulaiman/MM/UTKFace'

In [54]:
x2 = torch.load('all_age_gender_test_tensor.pt')
print(x2)

[tensor([1, 0]), tensor([1, 0]), tensor([1, 0]), tensor([1, 0]), tensor([1, 0]), tensor([1, 0]), tensor([1, 0]), tensor([1, 0]), tensor([1, 0]), tensor([1, 0]), tensor([1, 0]), tensor([1, 0]), tensor([1, 0]), tensor([1, 0]), tensor([1, 0]), tensor([1, 0]), tensor([1, 0]), tensor([1, 0]), tensor([1, 0]), tensor([1, 0]), tensor([1, 0]), tensor([1, 0]), tensor([1, 0]), tensor([1, 0]), tensor([1, 0]), tensor([1, 0]), tensor([1, 0]), tensor([1, 0]), tensor([1, 0]), tensor([1, 0]), tensor([1, 0]), tensor([1, 0]), tensor([1, 0]), tensor([1, 0]), tensor([1, 0]), tensor([1, 0]), tensor([1, 0]), tensor([1, 0]), tensor([1, 0]), tensor([1, 0]), tensor([1, 0]), tensor([1, 0]), tensor([1, 0]), tensor([1, 0]), tensor([1, 0]), tensor([1, 0]), tensor([1, 0]), tensor([1, 0]), tensor([1, 0]), tensor([1, 0]), tensor([1, 0]), tensor([1, 0]), tensor([1, 0]), tensor([1, 0]), tensor([1, 0]), tensor([1, 0]), tensor([1, 0]), tensor([1, 0]), tensor([1, 0]), tensor([1, 0]), tensor([1, 0]), tensor([1, 0]), tensor(

In [62]:
type(x2)

list

In [64]:
print(type(all_age_gender_test[0]))
print(type(x2[0]))

<class 'torch.Tensor'>
<class 'torch.Tensor'>


In [65]:
torch.save(all_age_gender_train, 'all_age_gender_train_tensor.pt')
torch.save(all_age_gender_val, 'all_age_gender_val_tensor.pt')

In [66]:
torch.save(all_images_data_train, 'all_images_data_train_tensor.pt')
torch.save(all_images_data_val, 'all_images_data_val_tensor.pt')
torch.save(all_images_data_test, 'all_images_data_test_tensor.pt')

In [67]:
x11 = torch.load('all_images_data_test_tensor.pt')
print(x11[0])

tensor([[[177, 181, 182,  ..., 119, 121, 122],
         [180, 184, 185,  ..., 119, 120, 121],
         [185, 189, 190,  ..., 118, 118, 118],
         ...,
         [163, 162, 160,  ..., 186, 184, 184],
         [164, 163, 161,  ..., 185, 184, 184],
         [164, 163, 162,  ..., 182, 182, 182]],

        [[162, 166, 169,  ...,  61,  65,  66],
         [165, 169, 172,  ...,  61,  64,  65],
         [170, 174, 177,  ...,  62,  62,  62],
         ...,
         [161, 160, 158,  ..., 173, 173, 175],
         [162, 161, 159,  ..., 172, 173, 175],
         [162, 161, 160,  ..., 169, 171, 173]],

        [[155, 159, 160,  ...,  24,  28,  29],
         [158, 162, 163,  ...,  24,  27,  28],
         [163, 167, 168,  ...,  25,  25,  25],
         ...,
         [172, 171, 169,  ..., 167, 167, 168],
         [173, 172, 170,  ..., 166, 169, 170],
         [173, 172, 171,  ..., 163, 167, 168]]], dtype=torch.uint8)


In [68]:
print(type(all_images_data_test))
print(type(x11))

<class 'list'>
<class 'list'>


In [69]:
print(all_images_data_test[0])

tensor([[[177, 181, 182,  ..., 119, 121, 122],
         [180, 184, 185,  ..., 119, 120, 121],
         [185, 189, 190,  ..., 118, 118, 118],
         ...,
         [163, 162, 160,  ..., 186, 184, 184],
         [164, 163, 161,  ..., 185, 184, 184],
         [164, 163, 162,  ..., 182, 182, 182]],

        [[162, 166, 169,  ...,  61,  65,  66],
         [165, 169, 172,  ...,  61,  64,  65],
         [170, 174, 177,  ...,  62,  62,  62],
         ...,
         [161, 160, 158,  ..., 173, 173, 175],
         [162, 161, 159,  ..., 172, 173, 175],
         [162, 161, 160,  ..., 169, 171, 173]],

        [[155, 159, 160,  ...,  24,  28,  29],
         [158, 162, 163,  ...,  24,  27,  28],
         [163, 167, 168,  ...,  25,  25,  25],
         ...,
         [172, 171, 169,  ..., 167, 167, 168],
         [173, 172, 170,  ..., 166, 169, 170],
         [173, 172, 171,  ..., 163, 167, 168]]], dtype=torch.uint8)


In [15]:
import torch
from torchvision import transforms
from PIL import Image

# Assuming img_tensor is your torch.Tensor object
img_tensor = torch.randn(3, 256, 256)  # Example tensor, replace with your own

# Convert the tensor to a PIL Image
to_pil = transforms.ToPILImage()
img_pil = to_pil(img_tensor)

# Now you can resize the PIL Image
resized_img = transforms.functional.resize(img_pil, (128, 128))  # Replace (128, 128) with your desired size


In [16]:
img_tensor.shape

torch.Size([3, 256, 256])

# class CustomDataset(Dataset)

In [17]:
import torch
from torch.utils.data import Dataset
from PIL import Image
from torchvision.transforms.functional import to_pil_image




class CustomDataset(Dataset):
    def __init__(self, your_data, your_labels, transform=None):
        self.data = your_data
        self.labels = your_labels
        self.transform = transform

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        sample = self.data[idx]
        # Convert the tensor to a PIL Image
        #to_pil = transforms.ToPILImage()
        #sample = to_pil(sample)
        sample = sample.float()
        #sample = sample.to(torch.float32)
        #sample = Image.open(sample)
        #sample = to_pil_image(sample)  # Convert tensor to PIL Image
        #sample = sample.permute(1, 2, 0).numpy().astype('uint8')
        #sample = Image.fromarray(sample)
        label = self.labels[idx]

        if self.transform:
            sample = self.transform(sample)

        return sample, label


In [18]:
from torchvision import transforms

# Example of using torchvision transforms with your custom dataset
#composed_transform = transforms.Compose([
 #   transforms.ToTensor(),
  #  transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
#])

composed_transform = transforms.Compose([
    #ConvertToPIL(),  # Convert tensor to PIL Image
    transforms.ToPILImage(),
    transforms.Resize((128,128)),  # transforms.Resize((64, 64)),
    transforms.ToTensor(),
    transforms.Normalize(mean=(0.5, 0.5, 0.5), std=(0.5, 0.5, 0.5)),
])

#transformed_dataset = CustomDataset(your_data, your_labels, transform=composed_transform)


In [19]:
# Assuming you have your data and labels ready
your_train_data = all_images_data_train # images  # Your data in the appropriate format
your_train_labels = all_age_gender_train #age_gender  # Corresponding labels

# Instantiate the custom dataset
custom_train_dataset = CustomDataset(your_train_data, your_train_labels, transform=composed_transform)


In [20]:
# Assuming you have your data and labels ready
your_val_data = all_images_data_val # images  # Your data in the appropriate format
your_val_labels = all_age_gender_val #age_gender  # Corresponding labels

# Instantiate the custom dataset
custom_val_dataset = CustomDataset(your_val_data, your_val_labels, transform=composed_transform)


In [21]:
# Assuming you have your data and labels ready
your_test_data = all_images_data_test # images  # Your data in the appropriate format
your_test_labels = all_age_gender_test #age_gender  # Corresponding labels

# Instantiate the custom dataset
custom_test_dataset = CustomDataset(your_test_data, your_test_labels, transform=composed_transform)


In [22]:

# Instantiate the custom dataset
#custom_dataset = CustomDataset(your_data, your_labels)

In [23]:
print(len(custom_test_dataset))

4741


In [24]:
custom_test_dataset

In [25]:
print(custom_test_dataset[0][0].shape)
print(custom_test_dataset[0][1].shape)

torch.Size([3, 128, 128])
torch.Size([2])


In [26]:
print('1: Young (age ≤ 35):', custom_test_dataset[0][1][0])

print('0: Old (age > 35):', custom_test_dataset[0][1][1])

1: Young (age ≤ 35): tensor(1)
0: Old (age > 35): tensor(0)


# Dataloaders:

In [27]:
from torch.utils.data import DataLoader
from copy import deepcopy

batch_size = 128
TEST_BS = 512

train_data_loader = DataLoader(custom_train_dataset, batch_size=batch_size, shuffle=True)
val_data_loader = DataLoader(custom_val_dataset, batch_size=TEST_BS, shuffle=True)
test_data_loader = DataLoader(custom_test_dataset, batch_size=1, shuffle=True)

In [28]:
for batch_idx, (images, labels) in enumerate(test_data_loader):
    # zero the parameter gradients
    #optimizer.zero_grad()

    # move to GPU
    images, labels = images, labels[:, 0]
    break

In [29]:
images, labels

(tensor([[[[ 0.5686,  0.5765,  0.5686,  ..., -0.1922, -0.1922, -0.2000],
           [ 0.5451,  0.5529,  0.5529,  ..., -0.1843, -0.1843, -0.1765],
           [ 0.5373,  0.5451,  0.5373,  ..., -0.1686, -0.1608, -0.1608],
           ...,
           [-0.3020, -0.2549, -0.1922,  ...,  0.5294,  0.5765,  0.6078],
           [-0.3020, -0.2471, -0.1686,  ...,  0.6000,  0.6157,  0.6157],
           [-0.3020, -0.2314, -0.1529,  ...,  0.6471,  0.6235,  0.5765]],
 
          [[ 0.7725,  0.7804,  0.7725,  ...,  0.1529,  0.1529,  0.1608],
           [ 0.7647,  0.7725,  0.7725,  ...,  0.1451,  0.1529,  0.1608],
           [ 0.7569,  0.7647,  0.7569,  ...,  0.1373,  0.1451,  0.1529],
           ...,
           [ 0.2078,  0.2549,  0.3176,  ...,  0.7176,  0.7569,  0.7804],
           [ 0.2078,  0.2627,  0.3412,  ...,  0.7725,  0.7882,  0.7804],
           [ 0.2078,  0.2784,  0.3569,  ...,  0.8196,  0.7882,  0.7412]],
 
          [[ 0.9529,  0.9608,  0.9529,  ...,  0.4353,  0.4431,  0.4431],
           [ 

In [30]:
len(train_data_loader)

112

In [31]:
print(images[0].shape)
print(labels[0])

torch.Size([3, 128, 128])
tensor(0)


In [32]:
len(val_data_loader)

10

In [33]:
custom_train_dataset

In [34]:
custom_train_dataset[0]

(tensor([[[ 1.0000,  0.9922,  0.9216,  ...,  0.7020,  0.6863,  0.6627],
          [ 0.9922,  0.9843,  0.9608,  ...,  0.6784,  0.6627,  0.6471],
          [ 0.9843,  0.9765,  0.9843,  ...,  0.6706,  0.6392,  0.6157],
          ...,
          [-1.0000, -1.0000, -1.0000,  ..., -0.0196, -0.0118, -0.0510],
          [-1.0000, -1.0000, -1.0000,  ..., -0.0196,  0.0118, -0.0588],
          [-1.0000, -1.0000, -1.0000,  ..., -0.0196,  0.0431, -0.0196]],
 
         [[-0.2078,  0.3255,  0.8510,  ...,  0.7804,  0.7647,  0.7412],
          [-0.2157,  0.9451,  0.8039,  ...,  0.7569,  0.7412,  0.7255],
          [-0.2157,  0.6863,  0.0431,  ...,  0.7490,  0.7176,  0.6941],
          ...,
          [-1.0000,  0.4353,  1.0000,  ..., -0.1529, -0.1373, -0.1608],
          [-1.0000,  0.4353,  1.0000,  ..., -0.1529, -0.1216, -0.1765],
          [-1.0000,  0.4353,  1.0000,  ..., -0.1608, -0.0980, -0.1529]],
 
         [[-1.0000, -0.8039,  0.4118,  ...,  0.7961,  0.7804,  0.7569],
          [-0.4353, -0.4196,

In [35]:
from models import MyResNet, ConvNet
import torch.nn as nn

import torch.optim as optim
from tqdm import tqdm

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

cuda


In [36]:
len(train_data_loader)

112

In [37]:
model = MyResNet(num_classes=2, pretrain=False)
# model = ConvNet(num_classes=2)
model = model.cuda()
criterion = nn.NLLLoss()

In [38]:
from torch.optim import Adam
from time import sleep
# https://adamoudad.github.io/posts/progress_bar_with_tqdm/
def train_per_epoch_tqdm_2(model, optimizer, criterion, epoch, num_epochs):
    model.train()
    epoch_loss = 0.0
    epoch_acc = 0.0

    correct_predictions = 0
    total_samples = 0

    with tqdm(train_data_loader, unit="batch") as tepoch:
        for images, labels in tepoch:
            tepoch.set_description(f"Epoch {epoch}")
                
            optimizer.zero_grad()

            # move to GPU
            images, labels = images.to(device), labels[:, 0].to(device)

            # forward
            outputs = model.forward(images)

            loss = criterion(outputs, labels)

            _, preds = torch.max(outputs.data, 1)

            loss.backward()
            optimizer.step()

            epoch_loss += loss.item()
            epoch_acc += torch.sum(preds == labels).item()

            # Update counts for accuracy calculation
            total_samples += labels.size(0)
            correct_predictions += torch.sum(preds == labels).item()
            # Calculate accuracy for this batch
            batch_accuracy = (correct_predictions / total_samples) * 100
            
            #tepoch.set_postfix(loss=epoch_loss, accuracy=epoch_acc)
            tepoch.set_postfix(loss=loss.item(), accuracy=batch_accuracy) 
            sleep(0.1)
    epoch_loss /= len(train_data_loader)
    epoch_acc = (epoch_acc / len(train_data_loader))
    print('epoch_acc:', epoch_acc)

    accuracy_all = (correct_predictions / total_samples) * 100
    print(f"Accuracy after all batches: {accuracy_all:.2f}%")


    print('TRAINING Epoch %d/%d Loss %.4f Accuracy %.4f' % (epoch, num_epochs, epoch_loss, epoch_acc))

In [39]:
def valid_per_epoch(model, epoch, num_epochs, criterion):
    model.eval()
    epoch_loss = 0.0
    epoch_acc = 0.0

    correct_predictions = 0
    total_samples = 0

    for batch_idx, (images, labels) in enumerate(val_data_loader):
        # move to GPU
        images, labels = images.to(device), labels[:, 0].to(device)

        # forward
        outputs = model.forward(images)

        loss = criterion(outputs, labels)

        _, preds = torch.max(outputs.data, 1)

        epoch_loss += loss.item()
        epoch_acc += torch.sum(preds == labels).item()


        # Update counts for accuracy calculation
        total_samples += labels.size(0)
        correct_predictions += torch.sum(preds == labels).item()
        # Calculate accuracy for this batch
        batch_accuracy = (correct_predictions / total_samples) * 100

    epoch_loss /= len(val_data_loader)
    epoch_acc /= len(val_data_loader)


    accuracy_all = (correct_predictions / total_samples) * 100
    print(f"Accuracy after all batches: {accuracy_all:.2f}%")

    print('VALID Epoch %d/%d Loss %.4f Accuracy %.4f' % (epoch, num_epochs, epoch_loss, epoch_acc))

    return epoch_loss

In [40]:
#########
# Training #
#########
NUM_EPOCHS = 50
losses = []
trigger_times = 0
best_loss = 1e9
best_model = None
optimizer = optim.SGD(model.parameters(), lr=1e-3, momentum=0.9, weight_decay=5e-4)
scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=20, gamma=0.5, last_epoch=-1)

for epoch in range(NUM_EPOCHS):
    train_per_epoch_tqdm_2(model, optimizer, criterion, epoch + 1, NUM_EPOCHS)
    epoch_loss = valid_per_epoch(model, epoch + 1, NUM_EPOCHS, criterion)
    losses.append(epoch_loss)
    if epoch_loss < best_loss and epoch > 5:
        best_model = deepcopy(model)
        best_loss = epoch_loss
    # Early Stop
    if (epoch > 20) and (losses[-1] >= losses[-2]):
        trigger_times += 1
        if trigger_times > 2:
            break
    else:
        trigger_times = 0

    scheduler.step()

Epoch 1: 100%|██████████| 112/112 [01:34<00:00,  1.18batch/s, accuracy=64.8, loss=0.599]


epoch_acc: 82.30357142857143
Accuracy after all batches: 64.81%
TRAINING Epoch 1/50 Loss 0.6297 Accuracy 82.3036
Accuracy after all batches: 69.44%
VALID Epoch 1/50 Loss 0.5784 Accuracy 329.2000


Epoch 2: 100%|██████████| 112/112 [01:26<00:00,  1.29batch/s, accuracy=72.4, loss=0.536]


epoch_acc: 91.95535714285714
Accuracy after all batches: 72.41%
TRAINING Epoch 2/50 Loss 0.5456 Accuracy 91.9554
Accuracy after all batches: 72.83%
VALID Epoch 2/50 Loss 0.5505 Accuracy 345.3000


Epoch 3: 100%|██████████| 112/112 [01:18<00:00,  1.42batch/s, accuracy=77.1, loss=0.555]


epoch_acc: 97.96428571428571
Accuracy after all batches: 77.14%
TRAINING Epoch 3/50 Loss 0.4808 Accuracy 97.9643
Accuracy after all batches: 74.58%
VALID Epoch 3/50 Loss 0.5145 Accuracy 353.6000


Epoch 4: 100%|██████████| 112/112 [01:20<00:00,  1.39batch/s, accuracy=79.7, loss=0.296]


epoch_acc: 101.16964285714286
Accuracy after all batches: 79.67%
TRAINING Epoch 4/50 Loss 0.4334 Accuracy 101.1696
Accuracy after all batches: 77.94%
VALID Epoch 4/50 Loss 0.4558 Accuracy 369.5000


Epoch 5: 100%|██████████| 112/112 [01:19<00:00,  1.41batch/s, accuracy=82.3, loss=0.246]


epoch_acc: 104.50892857142857
Accuracy after all batches: 82.30%
TRAINING Epoch 5/50 Loss 0.3898 Accuracy 104.5089
Accuracy after all batches: 78.59%
VALID Epoch 5/50 Loss 0.4431 Accuracy 372.6000


Epoch 6: 100%|██████████| 112/112 [01:18<00:00,  1.43batch/s, accuracy=84.5, loss=0.225]


epoch_acc: 107.32142857142857
Accuracy after all batches: 84.51%
TRAINING Epoch 6/50 Loss 0.3440 Accuracy 107.3214
Accuracy after all batches: 80.78%
VALID Epoch 6/50 Loss 0.4272 Accuracy 383.0000


Epoch 7: 100%|██████████| 112/112 [01:20<00:00,  1.40batch/s, accuracy=87.1, loss=0.157]


epoch_acc: 110.66964285714286
Accuracy after all batches: 87.15%
TRAINING Epoch 7/50 Loss 0.2974 Accuracy 110.6696
Accuracy after all batches: 80.34%
VALID Epoch 7/50 Loss 0.4252 Accuracy 380.9000


Epoch 8: 100%|██████████| 112/112 [01:20<00:00,  1.39batch/s, accuracy=89.9, loss=0.284]


epoch_acc: 114.16071428571429
Accuracy after all batches: 89.90%
TRAINING Epoch 8/50 Loss 0.2477 Accuracy 114.1607
Accuracy after all batches: 80.00%
VALID Epoch 8/50 Loss 0.4432 Accuracy 379.3000


Epoch 9: 100%|██████████| 112/112 [01:19<00:00,  1.42batch/s, accuracy=92.3, loss=0.259]


epoch_acc: 117.21428571428571
Accuracy after all batches: 92.30%
TRAINING Epoch 9/50 Loss 0.1994 Accuracy 117.2143
Accuracy after all batches: 80.97%
VALID Epoch 9/50 Loss 0.4589 Accuracy 383.9000


Epoch 10: 100%|██████████| 112/112 [01:18<00:00,  1.42batch/s, accuracy=95, loss=0.194]  


epoch_acc: 120.59821428571429
Accuracy after all batches: 94.97%
TRAINING Epoch 10/50 Loss 0.1449 Accuracy 120.5982
Accuracy after all batches: 80.64%
VALID Epoch 10/50 Loss 0.5086 Accuracy 382.3000


Epoch 11: 100%|██████████| 112/112 [01:18<00:00,  1.43batch/s, accuracy=96.8, loss=0.107] 


epoch_acc: 122.90178571428571
Accuracy after all batches: 96.78%
TRAINING Epoch 11/50 Loss 0.1009 Accuracy 122.9018
Accuracy after all batches: 78.23%
VALID Epoch 11/50 Loss 0.6091 Accuracy 370.9000


Epoch 12: 100%|██████████| 112/112 [01:18<00:00,  1.42batch/s, accuracy=98.5, loss=0.904] 


epoch_acc: 125.07142857142857
Accuracy after all batches: 98.49%
TRAINING Epoch 12/50 Loss 0.0707 Accuracy 125.0714
Accuracy after all batches: 78.57%
VALID Epoch 12/50 Loss 0.7869 Accuracy 372.5000


Epoch 13: 100%|██████████| 112/112 [01:17<00:00,  1.44batch/s, accuracy=97, loss=0.0771]  


epoch_acc: 123.16071428571429
Accuracy after all batches: 96.98%
TRAINING Epoch 13/50 Loss 0.0881 Accuracy 123.1607
Accuracy after all batches: 81.00%
VALID Epoch 13/50 Loss 0.6354 Accuracy 384.0000


Epoch 14: 100%|██████████| 112/112 [01:19<00:00,  1.41batch/s, accuracy=99.1, loss=0.0188]


epoch_acc: 125.83035714285714
Accuracy after all batches: 99.09%
TRAINING Epoch 14/50 Loss 0.0396 Accuracy 125.8304
Accuracy after all batches: 80.28%
VALID Epoch 14/50 Loss 0.6410 Accuracy 380.6000


Epoch 15: 100%|██████████| 112/112 [01:18<00:00,  1.42batch/s, accuracy=99.6, loss=0.0297]


epoch_acc: 126.45535714285714
Accuracy after all batches: 99.58%
TRAINING Epoch 15/50 Loss 0.0241 Accuracy 126.4554
Accuracy after all batches: 81.04%
VALID Epoch 15/50 Loss 0.6862 Accuracy 384.2000


Epoch 16: 100%|██████████| 112/112 [01:20<00:00,  1.40batch/s, accuracy=99.6, loss=0.42]   


epoch_acc: 126.53571428571429
Accuracy after all batches: 99.64%
TRAINING Epoch 16/50 Loss 0.0269 Accuracy 126.5357
Accuracy after all batches: 79.71%
VALID Epoch 16/50 Loss 0.7462 Accuracy 377.9000


Epoch 17: 100%|██████████| 112/112 [01:19<00:00,  1.41batch/s, accuracy=98.1, loss=0.062] 


epoch_acc: 124.60714285714286
Accuracy after all batches: 98.12%
TRAINING Epoch 17/50 Loss 0.0640 Accuracy 124.6071
Accuracy after all batches: 80.91%
VALID Epoch 17/50 Loss 0.6739 Accuracy 383.6000


Epoch 18: 100%|██████████| 112/112 [01:19<00:00,  1.41batch/s, accuracy=99.3, loss=0.823]  


epoch_acc: 126.125
Accuracy after all batches: 99.32%
TRAINING Epoch 18/50 Loss 0.0394 Accuracy 126.1250
Accuracy after all batches: 80.47%
VALID Epoch 18/50 Loss 0.8128 Accuracy 381.5000


Epoch 19: 100%|██████████| 112/112 [01:21<00:00,  1.38batch/s, accuracy=96.7, loss=0.12]  


epoch_acc: 122.75892857142857
Accuracy after all batches: 96.67%
TRAINING Epoch 19/50 Loss 0.0919 Accuracy 122.7589
Accuracy after all batches: 80.13%
VALID Epoch 19/50 Loss 0.6998 Accuracy 379.9000


Epoch 20: 100%|██████████| 112/112 [01:19<00:00,  1.40batch/s, accuracy=99, loss=0.3]     


epoch_acc: 125.70535714285714
Accuracy after all batches: 98.99%
TRAINING Epoch 20/50 Loss 0.0399 Accuracy 125.7054
Accuracy after all batches: 80.30%
VALID Epoch 20/50 Loss 0.8039 Accuracy 380.7000


Epoch 21: 100%|██████████| 112/112 [01:22<00:00,  1.37batch/s, accuracy=99.5, loss=0.0664] 


epoch_acc: 126.3125
Accuracy after all batches: 99.47%
TRAINING Epoch 21/50 Loss 0.0226 Accuracy 126.3125
Accuracy after all batches: 81.52%
VALID Epoch 21/50 Loss 0.7482 Accuracy 386.5000


Epoch 22: 100%|██████████| 112/112 [01:20<00:00,  1.38batch/s, accuracy=99.8, loss=0.157]  


epoch_acc: 126.6875
Accuracy after all batches: 99.76%
TRAINING Epoch 22/50 Loss 0.0159 Accuracy 126.6875
Accuracy after all batches: 81.52%
VALID Epoch 22/50 Loss 0.6793 Accuracy 386.5000


Epoch 23: 100%|██████████| 112/112 [01:19<00:00,  1.40batch/s, accuracy=99.7, loss=0.0229] 


epoch_acc: 126.66964285714286
Accuracy after all batches: 99.75%
TRAINING Epoch 23/50 Loss 0.0145 Accuracy 126.6696
Accuracy after all batches: 81.84%
VALID Epoch 23/50 Loss 0.7261 Accuracy 388.0000


Epoch 24: 100%|██████████| 112/112 [01:21<00:00,  1.37batch/s, accuracy=99.7, loss=0.00323]


epoch_acc: 126.65178571428571
Accuracy after all batches: 99.73%
TRAINING Epoch 24/50 Loss 0.0142 Accuracy 126.6518
Accuracy after all batches: 81.19%
VALID Epoch 24/50 Loss 0.7276 Accuracy 384.9000


Epoch 25: 100%|██████████| 112/112 [01:18<00:00,  1.43batch/s, accuracy=99.8, loss=0.0669] 


epoch_acc: 126.70535714285714
Accuracy after all batches: 99.78%
TRAINING Epoch 25/50 Loss 0.0100 Accuracy 126.7054
Accuracy after all batches: 81.33%
VALID Epoch 25/50 Loss 0.7276 Accuracy 385.6000


In [ ]:
model

In [42]:
pwd

'/gpfs/space/home/sulaiman/MM/UTKFace'

In [250]:
cd ..

c:\MM\Tools\PyTorch\PyTorch Fundamentals\Local_CONDA_Env\Last-Layer Fairness Fine-tuning is Simple and Effective for Neural Networks


In [41]:
state = {
        'epoch': epoch,
        'state_dict': model.state_dict(),
        'optimizer': optimizer.state_dict(),
}

savepath='checkpoint_128s_50Epochs.t7'
torch.save(state,savepath)

In [43]:
pwd

'/gpfs/space/home/sulaiman/MM/UTKFace'

In [44]:
model = MyResNet(num_classes=2, pretrain=False)
# model = ConvNet(num_classes=2)
model = model.cuda()
criterion = nn.NLLLoss()

optimizer = optim.SGD(model.parameters(), lr=1e-3, momentum=0.9, weight_decay=5e-4)

In [45]:
checkpoint = torch.load('checkpoint_128s_50Epochs.t7')
model.load_state_dict(checkpoint['state_dict'])
optimizer.load_state_dict(checkpoint['optimizer'])
epoch = checkpoint['epoch']

In [46]:
epoch = 0
NUM_EPOCHS = 1

epoch_loss = valid_per_epoch(model, epoch + 1, NUM_EPOCHS, criterion)

Accuracy after all batches: 81.33%
VALID Epoch 1/1 Loss 0.7121 Accuracy 385.6000


In [257]:
#########
# Training #
#########
NUM_EPOCHS = 10
losses = []
trigger_times = 0
best_loss = 1e9
best_model = None
optimizer = optim.SGD(model.parameters(), lr=1e-3, momentum=0.9, weight_decay=5e-4)
scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=20, gamma=0.5, last_epoch=-1)

for epoch in range(NUM_EPOCHS):
    train_per_epoch_tqdm_2(model, optimizer, criterion, epoch + 1, NUM_EPOCHS)
    epoch_loss = valid_per_epoch(model, epoch + 1, NUM_EPOCHS, criterion)
    losses.append(epoch_loss)
    if epoch_loss < best_loss and epoch > 5:
        best_model = deepcopy(model)
        best_loss = epoch_loss
    # Early Stop
    if (epoch > 20) and (losses[-1] >= losses[-2]):
        trigger_times += 1
        if trigger_times > 2:
            break
    else:
        trigger_times = 0

    scheduler.step()

Epoch 1: 100%|██████████| 28/28 [02:06<00:00,  4.53s/batch, accuracy=89.5, loss=0.273]


epoch_acc: 454.64285714285717
Accuracy after all batches: 89.50%
TRAINING Epoch 1/10 Loss 0.2740 Accuracy 454.6429
Accuracy after all batches: 75.57%
VALID Epoch 1/10 Loss 0.5012 Accuracy 1194.3333


Epoch 2: 100%|██████████| 28/28 [02:11<00:00,  4.69s/batch, accuracy=91.1, loss=0.269]


epoch_acc: 462.60714285714283
Accuracy after all batches: 91.07%
TRAINING Epoch 2/10 Loss 0.2473 Accuracy 462.6071
Accuracy after all batches: 74.90%
VALID Epoch 2/10 Loss 0.5181 Accuracy 1183.6667


Epoch 3: 100%|██████████| 28/28 [02:17<00:00,  4.91s/batch, accuracy=93, loss=0.243]  


epoch_acc: 472.39285714285717
Accuracy after all batches: 93.00%
TRAINING Epoch 3/10 Loss 0.2102 Accuracy 472.3929
Accuracy after all batches: 74.79%
VALID Epoch 3/10 Loss 0.5434 Accuracy 1182.0000


Epoch 4: 100%|██████████| 28/28 [02:27<00:00,  5.28s/batch, accuracy=94.5, loss=0.167]


epoch_acc: 480.07142857142856
Accuracy after all batches: 94.51%
TRAINING Epoch 4/10 Loss 0.1790 Accuracy 480.0714
Accuracy after all batches: 76.12%
VALID Epoch 4/10 Loss 0.5195 Accuracy 1203.0000


Epoch 5: 100%|██████████| 28/28 [02:15<00:00,  4.82s/batch, accuracy=96.4, loss=0.155]


epoch_acc: 489.57142857142856
Accuracy after all batches: 96.38%
TRAINING Epoch 5/10 Loss 0.1465 Accuracy 489.5714
Accuracy after all batches: 77.47%
VALID Epoch 5/10 Loss 0.5168 Accuracy 1224.3333


Epoch 6: 100%|██████████| 28/28 [02:13<00:00,  4.78s/batch, accuracy=97.5, loss=0.117]


epoch_acc: 495.2142857142857
Accuracy after all batches: 97.49%
TRAINING Epoch 6/10 Loss 0.1178 Accuracy 495.2143
Accuracy after all batches: 77.09%
VALID Epoch 6/10 Loss 0.5482 Accuracy 1218.3333


Epoch 7: 100%|██████████| 28/28 [02:21<00:00,  5.06s/batch, accuracy=98.6, loss=0.0955]


epoch_acc: 500.85714285714283
Accuracy after all batches: 98.60%
TRAINING Epoch 7/10 Loss 0.0904 Accuracy 500.8571
Accuracy after all batches: 74.56%
VALID Epoch 7/10 Loss 0.6367 Accuracy 1178.3333


Epoch 8: 100%|██████████| 28/28 [02:08<00:00,  4.60s/batch, accuracy=99.1, loss=0.0608]


epoch_acc: 503.60714285714283
Accuracy after all batches: 99.14%
TRAINING Epoch 8/10 Loss 0.0700 Accuracy 503.6071
Accuracy after all batches: 75.49%
VALID Epoch 8/10 Loss 0.6648 Accuracy 1193.0000


Epoch 9: 100%|██████████| 28/28 [02:26<00:00,  5.23s/batch, accuracy=99.5, loss=0.0509]


epoch_acc: 505.5357142857143
Accuracy after all batches: 99.52%
TRAINING Epoch 9/10 Loss 0.0541 Accuracy 505.5357
Accuracy after all batches: 75.49%
VALID Epoch 9/10 Loss 0.6700 Accuracy 1193.0000


Epoch 10: 100%|██████████| 28/28 [02:20<00:00,  5.03s/batch, accuracy=99.7, loss=0.0431]


epoch_acc: 506.42857142857144
Accuracy after all batches: 99.70%
TRAINING Epoch 10/10 Loss 0.0415 Accuracy 506.4286
Accuracy after all batches: 75.38%
VALID Epoch 10/10 Loss 0.6908 Accuracy 1191.3333


In [258]:
state = {
        'epoch': epoch,
        'state_dict': model.state_dict(),
        'optimizer': optimizer.state_dict(),
}

savepath='checkpoint_20Epochs.t7'
torch.save(state,savepath)